### PR TITLE
Correctly scale samples before passing to libFLAC

### LINKED ISSUE #452: FLAC encoder is broken
Hi,

I recently discovered that the FLAC and OggFLAC encoders are broken for all bit depths except 32-bit.
The processing format for these encoders is configured as unpacked signed int with bytes aligned low.
When the samples are fed to `FLAC__stream_encoder_process_interleaved`, the samples are interpreted as int32 without doing any sign extension.
For example with a 16-bit depth, the PCM converter may produce a 0xFFFF sample that will be interpreted as (int32)65535 instead of -1 and the encoding will fail.

One possible fix is to produce aligned-high samples and shift them right by (32 - bit_depth) before feeding the encoder. However I'm not sure if this is the best/fastest solution.

### PR DESCRIPTION
**Pull request by sbooth**
Fixes #452

### CODE REVIEW

File: Sources/CSFBAudioEngine/Encoders/SFBFLACEncoder.mm [hunk 1]
```diff
@@ -392,11 +395,56 @@ - (BOOL)encodeFromBuffer:(AVAudioPCMBuffer *)buffer frameLength:(AVAudioFrameCou
...
+				os_log_error(gSFBAudioEncoderLog, "FLAC__stream_encoder_process_interleaved failed: %{public}s", FLAC__stream_encoder_get_resolved_state_string(_flac.get()));
+				if(error)
+					*error = [NSError errorWithDomain:SFBAudioEncoderErrorDomain code:SFBAudioEncoderErrorCodeInternalError userInfo:nil];
+				return NO;
+			}
+
+			framesRemaining -= frameCount;
+		}
+	}
+	// Pass 32-bit samples straight through
```
Comment (jlama) [inline Sources/CSFBAudioEngine/Encoders/SFBFLACEncoder.mm:440]: It looks unnecessarily complex to me. Any reason not to modify the buffer in place?
Something like this:
```cpp
int32_t *data = (int32_t *)(buffer.mutableAudioBufferList->mBuffers[0].mData);
const auto bps = _processingFormat.streamDescription->mBitsPerChannel;
if (bps < 32) {
  const auto shift = 32 - bps;
  for (int i = 0; i < frameLength * buffer.stride; i++)
    data[i] >>= shift;
}
if(!FLAC__stream_encoder_process_interleaved(_flac.get(), data, frameLength)) {
...
}
```

**Review by jlama — COMMENTED** [review]
Thanks for your work. I added a comment inline.

File: Sources/CSFBAudioEngine/Encoders/SFBFLACEncoder.mm (hunk 1 above)
Comment (sbooth) [reply Sources/CSFBAudioEngine/Encoders/SFBFLACEncoder.mm:440]: I originally wrote similar code to modify the buffer in place. I changed it to the current implementation because it seems possible that the caller would want to reuse that buffer with multiple encoders which could lead to unexpected results.

Comment (jlama) [reply Sources/CSFBAudioEngine/Encoders/SFBFLACEncoder.mm:440]: Alright, I tested the code with the FLAC "verify encoding" setting enabled and it seems to work fine.
